name: generator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: generat chinaese readme
        uses: sz9751210/yaml-readme@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: 'items/*/*.yaml'
          template: 'template/README.tpl'
          output: 'README.md'
          username: sz9751210
          org: sz9751210
          repo: obsidian-plugins
          sortby: '!zh'
          groupby: kind
          header: false